development:
  adapter: redis

test:
  adapter: test

production:
  adapter: redis
  url: redis://redistogo:e437144b2323b0f2250b22b1cfc68dc0@pike.redistogo.com:10788/
  channel_prefix: derp_app_production
